---
title: "Simulations"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MASS)
library(ggplot2)
library(plyr)
```

# Read and filter the data
```{r}
data <- read_csv("Data/game.csv")
data <- data %>% filter(data$season == 20132014, data$home_team_id %in% c(seq(1,30), 52), data$away_team_id %in% c(seq(1,30), 52), data$type == 'R')
data$home_team_id[data$home_team_id == 52] <- 11
data$away_team_id[data$away_team_id == 52] <- 11
```

# The Model
```{r}
set.seed(405)
# There are three key parameters: the probability that the worst team in the league beats the best team in a random game (given by 'p'), the standard deviation in game-to-game performance levels for each team (given by 'tao'), and the standard deviation in the team talent levels (given by 'sigma'). We as the researchers choose a value for p or the ratio of tao and sigma.
p = 0.25
tao = 4.28
sigma = 1

# Calculate tie threshhold.
alpha <- qnorm(0.612, 0, sqrt(2 * (tao^2 + sigma^2)))

nloop <- 1000
oldGap <- rep(NA, nloop)
newGap <- rep(NA, nloop)
seedPoints <- data.frame(integer())

for (i in 1:nloop) {
  season <- simulateSeason()
  points <- calcTotalPoints(season)
  oldEast <- returnOldEastern(points)
  oldWest <- returnOldWestern(points)
  newEast <- returnNewEastern(points)
  newWest <- returnNewWestern(points)
  oldGap[i] <- oldEast[8,2] - oldWest[8,2]
  newGap[i] <- newEast[8,2] - newWest[8,2]
  allTeams <- rbind(newEast, newWest)
  allTeams <- allTeams[order(-allTeams$totalPoints),]
  seeds <- data.frame(seedPlace = seq(1,30), points = allTeams$totalPoints)
  seedPoints <- rbind(seedPoints, seeds)
}

df <- data.frame(Rule_Type = rep(c("Old alignment & rules", "New alignment & rules"), each = nloop), gap = c(oldGap, newGap))
dfDat <- ddply(df, "Rule_Type", summarise, grp.mean=mean(gap))

ggplot(df, aes(x = gap, fill = Rule_Type)) +
  geom_density(alpha = 0.4) +
  geom_vline(data = dfDat, aes(xintercept = grp.mean, color = Rule_Type), linetype = "dashed") +
  xlab("Conference gap") +
  ylab("Density")

ggplot(seedPoints, aes(x = seedPlace, y = points, group = seedPlace)) +
  geom_boxplot() +
  coord_flip()


c(mean(oldGap), mean(newGap), mean(newGap - oldGap))
```


# Simulating a season
```{r}
simulateSeason <- function() {
  # Draw a "team quality" value for all teams.
  teamQuality <- rnorm(30, 0, sigma)
  
  # Create overall games matrix with format:
  # GAME | TEAM 1 | TEAM 2 | GAMMA 1 | GAMMA 2 | GAMMA 1 - GAMMA 2 | OUTCOME 1 | OUTCOME 2
  # Where 'outcome' is the number of points awarded to their respective teams
  games <- list(seq(1, dim(data[1])[1]), rep(0, dim(data[1])[1]), rep(0, dim(data[1])[1]), rep(0, dim(data[1])[1]), rep(0, dim(data[1])[1]), rep(0, dim(data[1])[1]), rep(0, dim(data[1])[1]), rep(0, dim(data[1])[1]))
  
  # Go through the games
  for (game in 1:length(games[[1]])) {
    
    # Get the teams for each game and put them in the games matrix
    homeTeam <- getHomeTeam(game)
    awayTeam <- getAwayTeam(game)
    
    games[[2]][game] <- homeTeam
    games[[3]][game] <- awayTeam
      
    # Extract game performance values -- insert into games matrix
    homePerformance <- rnorm(n = 1, teamQuality[homeTeam], tao)
    awayPerformance <- rnorm(n = 1, teamQuality[awayTeam], tao)
    
    games[[4]][game] <- homePerformance
    games[[5]][game] <- awayPerformance
    
    # Check if there is a tie -- store difference for later
    games[[6]][game] <- homePerformance - awayPerformance
  }
  a <- mean(games[[6]])
  b <- max(games[[6]])
  
  # Go through and calculate outcomes
  for (game in 1:length(games[[1]])) {
    # If there is a tie award 2 points to the 'winner'
    if (abs(games[[6]][game]) >= alpha) {
      if (games[[6]][game] >= 0) {
        games[[7]][game] <- 2
      }
      else {
        games[[8]][game] <- 2
      }
    }
    # Else rescale performances and simulate a winner, giving two points to the winner and one to the loser
    else {
      zeta <- (games[[6]][game] - a) / b
      if (rbernoulli(1, p = zeta)) {
        games[[7]][game] <- 2
        games[[8]][game] <- 1
      }
      else {
        games[[7]][game] <- 1
        games[[8]][game] <- 2
      }
    }
  }
  return(games)
}
```

```{r}
# Get the sum of the points for each team. The return vector is sorted by team number value.
calcTotalPoints <- function(season){
  totalPoints <- rep(0, 30)
  for (game in 1:length(season[[1]])){
    totalPoints[season[[2]][game]] = totalPoints[season[[2]][game]] + season[[7]][game]
    totalPoints[season[[3]][game]] = totalPoints[season[[3]][game]] + season[[8]][game]
  }
  returnVec = data.frame("id" = seq(1,30), totalPoints, "Team Name" = c("New Jersey Devils", "NY Islanders", "NY Rangers", "Philadelphia Flyers", "Pittsburgh Penguins", "Boston Bruins", "Buffalo Sabres", "Montreal Canadiens", "Ottowa Senators", "Toronto Maple Leafs", "Winnipeg Jets", "Carolina Hurricanes", "Florida Panthers", "Tampa Bay Lightning", "Washington Capitals", "Chicago Blackhawks", "Detroit Red Wings", "Nashville Predators", "St Louis Blues", "Calgary Flames", "Colorado Avalanche", "Edmonton Oilers", "Vancouver Canucks", "Anaheim Ducks", "Dallas Stars", "LA Kings", "Phoenix Coyotes", "San Jose Sharks", "Columbus Blue Jackets", "Minnesota Wild"))

  return(returnVec)
}
```

```{r}
returnOldEastern <- function(points) {
  atlantic = points[points$id %in% c(1:5),]
  northeast = points[points$id %in% c(6:10),]
  southeast = points[points$id %in% c(11:15),]
  
  atlantic = atlantic[order(-atlantic$totalPoints),]
  northeast = northeast[order(-northeast$totalPoints),]
  southeast = southeast[order(-southeast$totalPoints),]
  
  wildcards = rbind(atlantic[3:5,],northeast[3:5,],southeast[3:5,])
  wildcards = wildcards[order(-wildcards$totalPoints),]
  
  top6 <- rbind(atlantic[1:2,],northeast[1:2,],southeast[1:2,])
  top6 = top6[order(-top6$totalPoints),]

  return(rbind(top6, wildcards))
}

returnOldWestern <- function(points) {
  central = points[points$id %in% c(16:19, 29),]
  northwest = points[points$id %in% c(20:23, 30),]
  pacific = points[points$id %in% c(24:28),]
  
  central = central[order(-central$totalPoints),]
  northwest = northwest[order(-northwest$totalPoints),]
  pacific = pacific[order(-pacific$totalPoints),]
  
  wildcards = rbind(central[3:5,],northwest[3:5,],pacific[3:5,])
  wildcards = wildcards[order(-wildcards$totalPoints),]
  
  top6 <- rbind(central[1:2,],northwest[1:2,],pacific[1:2,])
  top6 = top6[order(-top6$totalPoints),]

  return(rbind(top6, wildcards))
}

returnNewEastern <- function(points) {
  metro = points[points$id %in% c(1:5, 12, 15, 29),]
  atlantic = points[points$id %in% c(6:10, 13, 14, 17),]
  
  metro = metro[order(-metro$totalPoints),]
  atlantic = atlantic[order(-atlantic$totalPoints),]
  
  wildcards = rbind(metro[4:8,],atlantic[4:8,])
  wildcards = wildcards[order(-wildcards$totalPoints),]
  
  top6 <- rbind(metro[1:3,],atlantic[1:3,])
  top6 = top6[order(-top6$totalPoints),]

  return(rbind(top6, wildcards))
}

returnNewWestern <- function(points) {
  central = points[points$id %in% c(11, 16, 18, 19, 21, 25, 30),]
  pacific = points[points$id %in% c(20, 22, 23, 24, 26:28),]
  
  central = central[order(-central$totalPoints),]
  pacific = pacific[order(-pacific$totalPoints),]
  
  wildcards = rbind(central[4:7,],pacific[4:7,])
  wildcards = wildcards[order(-wildcards$totalPoints),]
  
  top6 <- rbind(central[1:3,],pacific[1:3,])
  top6 = top6[order(-top6$totalPoints),]

  return(rbind(top6, wildcards))
}
```


```{r}
seperateConf <- function(points){
  eastern = data.frame()
  western = data.frame()
  indexE = 1
  indexW = 1
  for (i in c(1:10, 12:15, 17, 29)){
    eastern[indexE, 1] = points[i, 1]
    eastern[indexE, 2] = points[i, 2]
    indexE = indexE + 1
  }
  
  for (i in c(11, 16, 18:28, 30)){
    western[indexW, 1] = points[i, 1]
    western[indexW, 2] = points[i, 2]
    indexW = indexW + 1
  }
  return(c(eastern, western))
}
```



# Helper functions
```{r}
getHomeTeam <- function(index) {
  return (data$home_team_id[index])
}

getAwayTeam <- function(index) {
  return (data$away_team_id[index])
}
```











