---
title: "insert title here"
author:
output: slidy_presentation 
---

## The National Hockey League (NHL)

- Each team plays 82 games per season
- This allows for every team to play each team at least twice
- The league is split up into two conferences, the East and the West, each with two divisions
-The East has the Metropolitan and the Atlantic divisions while the West has the Central and Pacific divisions.

## The Changes for the 2013-14 season

- Winnipeg Jets move from the Eastern to the Western confrence
- Columbus Blue jackets and Detroit Redwings move from the West to the East
- Each conference previoulsy had three divisions of five teams but these were condensed into the four divisions that currently exist

# Playoff Structure
- For the previous conference/division structure, the top two teams in each division secure a berth into the playoffs
- The remaining four slots are claimed by the two teams in each conference with the next highest point total regardles of the division. These are known as the wild cards.
- The process is similar with the new divisions in each conference
- Now the top three teams in each division secure a playoff berth and the wild cards are chosen using the same process as before

# The Reasoning for the Sampling

- Changes left the West with two divisions of 14 teams and the East with 2 divisions of 16 teams
- 8 teams from both conferences were garunteed to make the playoffs
- The sampling is meant to test whether or not it is more difficult to reach the playoffs as an eastern confrence team

# Extension 2017-18 season

- This season added the Vegas Golden Knights
- Now the West has one divion of 8 teams and one division of 7 teams
- This creates new probabilities for the required points to make it to the playoffs
